export const sources = {
  corps: { id:'corps', title:'Green Lantern Corps — Official DC Character', publisher:'DC', url:'https://www.dc.com/characters/green-lantern-corps', note:'Corps scale, sectors, Oa, Earth Lantern overview.' },
  hal: { id:'hal', title:'Green Lantern — Official DC Character', publisher:'DC', url:'https://www.dc.com/characters/green-lantern', note:'Hal Jordan biography and core powers.' },
  john: { id:'john', title:'DC Celebrates 50 Years of Green Lantern John Stewart', publisher:'DC', url:'https://www.dc.com/blog/2021/02/11/dc-celebrates-50-years-of-green-lantern-john-stewart-with-a-commemorative-hardcover', note:'John Stewart first appearance and legacy.' },
  guy: { id:'guy', title:'Behind the Bowl Cut: Everything You Need to Know About Guy Gardner', publisher:'DC', url:'https://www.dc.com/blog/2025/07/08/behind-the-bowl-cut-everything-you-need-to-know-about-guy-gardner', note:'Guy Gardner history, first appearance, roles and ring history.' },
  kyle: { id:'kyle', title:'Green With Creativity: The Five Best Green Lantern Constructs', publisher:'DC', url:'https://www.dc.com/blog/2024/03/14/green-with-creativity-the-five-best-green-lantern-constructs', note:'Kyle Rayner creativity and construct style.' },
  kyle2: { id:'kyle2', title:'What Your Favorite Green Lantern Says About You', publisher:'DC', url:'https://www.dc.com/blog/2025/02/12/what-your-favorite-green-lantern-says-about-you', note:'Kyle Rayner Torchbearer label and first appearance.' },
  simon: { id:'simon', title:'Simon Baz — Official DC Character', publisher:'DC', url:'https://www.dc.com/characters/simon-baz', note:'Simon Baz biography, powers and Sector 2814 context.' },
  jessica: { id:'jessica', title:'Jessica Cruz, the People’s Green Lantern', publisher:'DC', url:'https://www.dc.com/blog/2025/03/10/jessica-cruz-the-people-s-green-lantern', note:'Jessica Cruz origin, fear/courage themes and career overview.' },
  jo: { id:'jo', title:'Jo Mullein and Far Sector Are Out of This World', publisher:'DC', url:'https://www.dc.com/blog/2021/06/09/jo-mullein-and-far-sector-are-out-of-this-world', note:'Jo Mullein, Far Sector, Alan Scott history and construct examples.' },
  keli: { id:'keli', title:'Meet the Stars of the All-New Green Lantern Series', publisher:'DC', url:'https://www.dc.com/blog/2021/04/06/meet-the-stars-of-the-all-new-green-lantern-series', note:'Keli Quintela / Teen Lantern and Jo Mullein in the 2021 series.' },
  jade: { id:'jade', title:'Five Things to Know about Stargirl’s Jade', publisher:'DC', url:'https://www.dc.com/blog/2021/08/17/five-things-to-know-about-stargirls-jade', note:'Jade lineage and Green Lantern legacy context.' },
  spectrum: { id:'spectrum', title:'Editors Matt Idelson and Pat McCallum Discuss the Green Lantern Universe', publisher:'DC', url:'https://www.dc.com/blog/2012/08/27/editors-matt-idelson-and-pat-mc-callum-discuss-the-green-lantern-universe', note:'Seven-color emotional spectrum plus Black/White distinctions.' },
  sinestro: { id:'sinestro', title:'Sinestro — Official DC Character', publisher:'DC', url:'https://www.dc.com/characters/sinestro', note:'Sinestro origin, Sector 1417 and Sinestro Corps.' },
  glc2025: { id:'glc2025', title:'Green Lantern Corps #1 Announcement', publisher:'DC', url:'https://www.dc.com/blog/2024/11/15/green-lantern-corps-1-jeremy-adams-morgan-hampton-fernando-pasarin-and-oclair-albert-reunite-the-galaxy-s-greatest-ring-slingers-in-a-new-dc-all-in-series', note:'2025 Corps series roster and publication context.' },
  gl2021: { id:'gl2021', title:'Green Lantern #1 (2021)', publisher:'DC', url:'https://www.dc.com/comics/green-lantern-2021/green-lantern-1', note:'John, Keli and the United Planets-era Oa status quo.' },
  blackest: { id:'blackest', title:'Untold Tales of Blackest Night #1', publisher:'DC', url:'https://www.dc.com/comics/blackest-night-2009/untold-tales-of-blackest-night-1', note:'Black Lantern and emotional spectrum context.' },
  jadeKyle: { id:'jadeKyle', title:'DC Comics Presents: Green Lantern #1', publisher:'DC', url:'https://www.dc.com/comics/dc-comics-presents-2010/dc-comics-presents-green-lantern-1', note:'Kyle Rayner and Jade relationship / legacy context.' }
};

const art = (url, sourceUrl, alt, credit='DC promotional/editorial artwork; all rights remain with DC and the credited creators.') => ({ url, sourceUrl, alt, credit });

export const lanterns = [
  {
    slug:'hal-jordan', name:'Hal Jordan', alias:'The Emerald Knight', realName:'Harold “Hal” Jordan', era:'silver', status:'corps', sector:'2814', firstAppearance:'Showcase #22 (1959)', creators:['John Broome','Gil Kane'], affiliations:['Green Lantern Corps','Justice League'], abilities:['Power-ring hard-light constructs','Flight','Force fields','Energy projection','Universal translation'], constructStyle:'Direct, aerodynamic and pilot-minded constructs: aircraft, weapons, restraints and large-scale force applications.', stories:['Green Lantern: Rebirth','Sinestro Corps War','Blackest Night','War of the Green Lanterns'], relationships:['Abin Sur','Sinestro','Carol Ferris','John Stewart'], sourceIds:['hal','corps','glc2025'], summary:'A test pilot selected by Abin Sur’s ring, Hal became Earth’s defining Corps-era Green Lantern and a central figure in the modern mythology.', quote:'Fear is data. Will is the decision that comes after it.', artwork:art('https://static.dc.com/dc/files/default_images/Char_Thumb_GreenLantern_20200721_5f173ac65f56f7.70929296.jpg?w=640','https://www.dc.com/characters/green-lantern','Hal Jordan as Green Lantern')
  },
  {
    slug:'john-stewart', name:'John Stewart', alias:'The Architect', realName:'John Stewart', era:'bronze', status:'corps', sector:'2814', firstAppearance:'Green Lantern #87 (1971)', creators:["Dennis O'Neil",'Neal Adams'], affiliations:['Green Lantern Corps','Justice League','Darkstars'], abilities:['Power-ring constructs','Flight','Force fields','Tactical command','Architectural visualization'], constructStyle:'Precision-engineered constructs often described through his architectural and military perspective.', stories:['Mosaic','Green Lantern Corps','War of the Green Lanterns','Green Lantern: War Journal'], relationships:['Katma Tui','Hal Jordan','Guy Gardner','Kilowog'], sourceIds:['john','corps','glc2025'], summary:'Architect, veteran and commander whose analytical imagination makes his ring-work unusually structural and exact.', quote:'Build the solution before the crisis finishes drawing the problem.', artwork:art('https://static.dc.com/dc/files/default_images/John%2520Stewart%2520Crop_6024865444b7a3.86126476.jpg?w=1200','https://www.dc.com/blog/2021/02/11/dc-celebrates-50-years-of-green-lantern-john-stewart-with-a-commemorative-hardcover','John Stewart in Green Lantern uniform')
  },
  {
    slug:'guy-gardner', name:'Guy Gardner', alias:'The Wild Card', realName:'Guy Gardner', era:'bronze', status:'corps', sector:'2814', firstAppearance:'Green Lantern #59 (1968)', creators:['John Broome','Gil Kane'], affiliations:['Green Lantern Corps','Justice League International','Red Lantern Corps'], abilities:['Power-ring constructs','Flight','Force fields','Close-quarters combat'], constructStyle:'Blunt-force, aggressive and improvisational—less about elegance than overwhelming intent.', stories:['Justice League International','Green Lantern Corps','Red Lanterns','Green Lantern: Rebirth'], relationships:['Ice','Hal Jordan','John Stewart','Kilowog'], sourceIds:['guy','corps','glc2025'], summary:'Almost chosen before Hal, Guy evolved from substitute Lantern into one of the Corps’ most stubborn and battle-tested ring-slingers.', quote:'The ring responds to will. Subtlety is optional.', artwork:art('https://static.dc.com/2025-07/2025_07_08_GuyGardner101_Marquee_3x1.jpg?w=1200','https://www.dc.com/blog/2025/07/08/behind-the-bowl-cut-everything-you-need-to-know-about-guy-gardner','Guy Gardner editorial artwork')
  },
  {
    slug:'kyle-rayner', name:'Kyle Rayner', alias:'The Torchbearer', realName:'Kyle Rayner', era:'modern', status:'corps', sector:'2814', firstAppearance:'Green Lantern #48 (1994)', creators:['Ron Marz','Darryl Banks'], affiliations:['Green Lantern Corps','Justice League','New Guardians'], abilities:['Power-ring constructs','Flight','Force fields','Spectrum mastery'], constructStyle:'Illustrator-driven, elaborate and pop-culture literate constructs; creativity is his signature advantage.', stories:['Emerald Twilight','Circle of Fire','Ion','The New Guardians'], relationships:['Jade','Ganthet','Hal Jordan','Guy Gardner'], sourceIds:['kyle','kyle2','jadeKyle'], summary:'An artist handed the last functioning Green Lantern ring after the Corps’ collapse, Kyle became the Torchbearer and later rebuilt its legacy.', quote:'Imagination is not decoration. For a Lantern, it is engineering.'
  },
  {
    slug:'simon-baz', name:'Simon Baz', alias:'The Backup Plan', realName:'Simon Baz', era:'modern', status:'corps', sector:'2814', firstAppearance:'The New 52 Free Comic Book Day Special Edition #1 (2012)', creators:['Geoff Johns','Doug Mahnke'], affiliations:['Green Lantern Corps','Justice League of America'], abilities:['Hard-light constructs','Flight','Force fields','Healing','Precognitive flashes in some stories'], constructStyle:'Practical, grounded constructs shaped by survival instincts and a willingness to question the ring itself.', stories:['Rise of the Third Army','Green Lanterns','Phantom Lantern'], relationships:['Jessica Cruz','B’dg','Hal Jordan'], sourceIds:['simon','corps','glc2025'], summary:'A Detroit-area recruit whose early distrust of the ring made him one of Earth’s most unconventional Lanterns.', quote:'Trust is earned—even when the tool choosing you can rewrite physics.', artwork:art('https://static.dc.com/dc/files/default_images/Char_Thumb_SimonBaz_5fa21f06bfbd71.56108051.jpg?w=640','https://www.dc.com/characters/simon-baz','Simon Baz as Green Lantern')
  },
  {
    slug:'jessica-cruz', name:'Jessica Cruz', alias:'The Courage Lantern', realName:'Jessica Cruz', era:'modern', status:'corps', sector:'2814', firstAppearance:'Justice League #30 (2014)', creators:['Geoff Johns','Ethan Van Sciver','Ivan Reis'], affiliations:['Green Lantern Corps','Justice League','Justice League Odyssey'], abilities:['Hard-light constructs','Flight','Force fields','Exceptional resistance to fear'], constructStyle:'Adaptive and emotionally expressive, often emphasizing protection, mobility and overcoming fear rather than denying it.', stories:['Darkseid War','Green Lanterns','Justice League Odyssey','Green Lantern 2021 Annual'], relationships:['Simon Baz','Power Ring','John Stewart'], sourceIds:['jessica','glc2025'], summary:'Jessica’s defining Lantern trait is not fearlessness but courage: the repeated choice to act while fear is present.', quote:'Courage is not the absence of fear. It is movement through it.', artwork:art('https://static.dc.com/2025-03/20250310_DC_News_JessicaCruz1alt.jpg','https://www.dc.com/blog/2025/03/10/jessica-cruz-the-people-s-green-lantern','Jessica Cruz in Green Lantern uniform')
  },
  {
    slug:'jo-mullein', name:'Jo Mullein', alias:'Far Sector Lantern', realName:'Sojourner “Jo” Mullein', era:'modern', status:'corps', sector:'Far Sector / City Enduring assignment', firstAppearance:'Far Sector #1 (2019)', creators:['N. K. Jemisin','Jamal Campbell'], affiliations:['Green Lantern Corps'], abilities:['Experimental power ring','Constructs','Flight','Shielding','Investigative reconstruction'], constructStyle:'Detective-minded and highly imaginative—crime-scene reconstructions, shields, creatures and even mech-scale constructs.', stories:['Far Sector','Green Lantern (2021)','Green Lantern Corps (2025)'], relationships:['City Enduring','John Stewart','Keli Quintela'], sourceIds:['jo','keli','glc2025'], summary:'An ex-military, ex-NYPD investigator assigned to a distant civilization, Jo brought hard science-fiction detective energy into Green Lantern lore.', quote:'A construct can be evidence, shelter, a question—or a very large mech.', artwork:art('https://static.dc.com/sites/default/files/imce/2021/06-JUN/FarSector9_cov_60c037c2273675.76566215.jpg','https://www.dc.com/blog/2021/06/09/jo-mullein-and-far-sector-are-out-of-this-world','Jo Mullein on a Far Sector cover')
  },
  {
    slug:'alan-scott', name:'Alan Scott', alias:'The Golden Age Green Lantern', realName:'Alan Scott', era:'golden', status:'legacy', sector:'Earth / non-Corps tradition', firstAppearance:'All-American Comics #16 (1940)', creators:['Martin Nodell','Bill Finger'], affiliations:['Justice Society of America','All-Star Squadron'], abilities:['Mystic green flame','Energy constructs','Flight','Protective aura'], constructStyle:'Mystical green-flame manifestations rather than standard Corps technology.', stories:['All-American Comics','Justice Society of America','Green Lantern: Alan Scott'], relationships:['Jade','Obsidian','Justice Society'], sourceIds:['jo','jade'], summary:'The original Green Lantern predates the Corps-era concept. His power comes from a separate mystical tradition and should not be flattened into Sector 2814 Corps history.', quote:'Before Oa defined the symbol, Earth already had a green light of its own.'
  },
  {
    slug:'jade', name:'Jade', alias:'Green Lantern Legacy', realName:'Jennie-Lynn Hayden', era:'modern', status:'legacy', sector:'Earth / legacy', firstAppearance:'All-Star Squadron #25 (1983)', creators:['Roy Thomas','Jerry Ordway'], affiliations:['Infinity, Inc.','Justice Society of America','Outsiders','Green Lantern legacy'], abilities:['Green energy manipulation','Constructs','Flight','Energy projection'], constructStyle:'Innate green-energy constructs connected to her lineage rather than a conventional Corps ring for much of her history.', stories:['Infinity, Inc.','Green Lantern','Brightest Day','Infinite Frontier'], relationships:['Alan Scott','Obsidian','Kyle Rayner'], sourceIds:['jade','jadeKyle'], summary:'Alan Scott’s daughter and an important bridge between Earth’s mystical Green Lantern legacy and the wider modern mythology.', quote:'Legacy is not imitation. It is inherited light becoming something new.'
  },
  {
    slug:'keli-quintela', name:'Keli Quintela', alias:'Teen Lantern', realName:'Keli Quintela', era:'modern', status:'allied', sector:'Earth / Corps ally', firstAppearance:'Young Justice #1 (2019)', creators:['Brian Michael Bendis','Patrick Gleason'], affiliations:['Young Justice','Green Lantern Corps allies'], abilities:['Power gauntlet','Energy constructs','Flight','Force fields'], constructStyle:'Gauntlet-generated constructs with youthful improvisation; her technology is distinct from a standard Corps power ring.', stories:['Young Justice','Green Lantern (2021)','Green Lantern Corps (2025)'], relationships:['John Stewart','Jo Mullein','Simon Baz'], sourceIds:['keli','gl2021','glc2025'], summary:'A young hero wielding a homemade gauntlet linked to Green Lantern energy, Keli occupies a deliberately different place from conventional ring-selected Corps members.', quote:'A Lantern story can begin with a ring—or with the audacity to build your own way in.'
  },
  {
    slug:'kilowog', name:'Kilowog', alias:'Drill Sergeant of the Corps', realName:'Kilowog', era:'cosmic', status:'corps', sector:'Formerly 674', firstAppearance:'Green Lantern Corps #201 (1986)', creators:['Steve Englehart','Joe Staton'], affiliations:['Green Lantern Corps'], abilities:['Power-ring constructs','Flight','Force fields','Training and combat'], constructStyle:'Heavy-duty, practical constructs built for combat, rescue and training.', stories:['Green Lantern Corps','Sinestro Corps War','Blackest Night'], relationships:['Hal Jordan','Guy Gardner','Corps recruits'], sourceIds:['corps'], summary:'The Corps’ iconic trainer and one of its most recognizable alien veterans.', quote:'Every recruit learns that willpower still needs practice.'
  },
  {
    slug:'mogo', name:'Mogo', alias:'The Living Planet', realName:'Mogo', era:'cosmic', status:'corps', sector:'Mobile / planetary', firstAppearance:'Green Lantern #188 (1985)', creators:['Alan Moore','Dave Gibbons'], affiliations:['Green Lantern Corps'], abilities:['Planetary-scale ring energy','Guidance of power rings','Environmental control'], constructStyle:'Planetary-scale interventions rather than humanoid ring-slinging.', stories:['Mogo Doesn’t Socialize','Sinestro Corps War','Blackest Night'], relationships:['Green Lantern Corps'], sourceIds:['corps'], summary:'A sentient planet and Green Lantern whose scale changes what “member of the Corps” can mean.', quote:'Some Lanterns patrol worlds. One of them is a world.'
  }
];

export const villains = [
  { slug:'sinestro', name:'Sinestro', color:'#f6d945', role:'Fallen Lantern / founder of the Sinestro Corps', firstAppearance:'Green Lantern #7 (1961)', summary:'Former Green Lantern of Sector 1417 whose authoritarian pursuit of order led to exile and mastery of fear.', sourceIds:['sinestro','spectrum'] },
  { slug:'atrocitus', name:'Atrocitus', color:'#ff3b45', role:'Founder of the Red Lantern Corps', firstAppearance:'Green Lantern #25 (2007)', summary:'A survivor whose rage becomes both weapon and organizing principle.', sourceIds:['spectrum'] },
  { slug:'black-hand', name:'Black Hand', color:'#9da4ad', role:'Black Lantern catalyst', firstAppearance:'Green Lantern #29 (1964)', summary:'An enemy repeatedly tied to death-energy and the rise of the Black Lanterns.', sourceIds:['blackest','spectrum'] },
  { slug:'parallax', name:'Parallax', color:'#f6df49', role:'Fear entity', firstAppearance:'Green Lantern #50 (1994) / entity retcon later', summary:'The yellow fear entity that became central to the reinterpretation of Hal Jordan’s fall.', sourceIds:['spectrum'] },
  { slug:'nekron', name:'Nekron', color:'#cfd3d9', role:'Lord of the Unliving', firstAppearance:'Tales of the Green Lantern Corps #2 (1981)', summary:'A death-associated cosmic foe at the center of Blackest Night.', sourceIds:['blackest'] },
  { slug:'krona', name:'Krona', color:'#7ee8ff', role:'Guardian renegade', firstAppearance:'Green Lantern #40 (1965)', summary:'A Maltusian scientist whose forbidden investigation into creation repeatedly destabilized the universe.', sourceIds:['corps'] },
  { slug:'hector-hammond', name:'Hector Hammond', color:'#b8ef88', role:'Psionic adversary', firstAppearance:'Green Lantern #5 (1961)', summary:'A recurring Earth enemy whose expanded intellect and psionic powers make him a cerebral threat.', sourceIds:['hal'] }
];

export const spectrum = [
  { id:'rage', name:'Red', emotion:'Rage', color:'#ff334f', kind:'emotion', corps:'Red Lantern Corps', exemplar:'Atrocitus' },
  { id:'avarice', name:'Orange', emotion:'Avarice', color:'#ff8b2f', kind:'emotion', corps:'Orange Light', exemplar:'Larfleeze' },
  { id:'fear', name:'Yellow', emotion:'Fear', color:'#ffd84a', kind:'emotion', corps:'Sinestro Corps', exemplar:'Sinestro' },
  { id:'will', name:'Green', emotion:'Willpower', color:'#22f28d', kind:'emotion', corps:'Green Lantern Corps', exemplar:'Sector 2814' },
  { id:'hope', name:'Blue', emotion:'Hope', color:'#42a5ff', kind:'emotion', corps:'Blue Lantern Corps', exemplar:'Saint Walker' },
  { id:'compassion', name:'Indigo', emotion:'Compassion', color:'#7b65ff', kind:'emotion', corps:'Indigo Tribe', exemplar:'Indigo-1' },
  { id:'love', name:'Violet', emotion:'Love', color:'#ff5ac8', kind:'emotion', corps:'Star Sapphires', exemplar:'Carol Ferris' },
  { id:'death', name:'Black', emotion:'Death', color:'#88909a', kind:'metaphysical', corps:'Black Lanterns', exemplar:'Nekron' },
  { id:'life', name:'White', emotion:'Life', color:'#f6fbff', kind:'metaphysical', corps:'White Light', exemplar:'Life Entity' }
];

export const events = [
  { year:1940, title:'The First Green Lantern', era:'Golden Age', summary:'Alan Scott debuts in All-American Comics #16, establishing the name before the Corps mythology exists.', sourceIds:['jo'] },
  { year:1959, title:'A Cosmic Reinvention', era:'Silver Age', summary:'Hal Jordan and the Corps-era concept arrive in Showcase #22, reframing Green Lantern as intergalactic science fiction.', sourceIds:['corps','jo'] },
  { year:1971, title:'John Stewart Debuts', era:'Bronze Age', summary:'Green Lantern #87 introduces John Stewart, who grows into one of the franchise’s defining Lanterns.', sourceIds:['john'] },
  { year:1994, title:'Emerald Twilight / Kyle Rayner', era:'Modern', summary:'The Corps collapses and Kyle Rayner inherits the surviving ring, becoming the Torchbearer of a drastically changed status quo.', sourceIds:['kyle2'] },
  { year:2004, title:'Green Lantern: Rebirth', era:'Modern', summary:'Hal Jordan’s return reassembles core Green Lantern mythology and recasts Parallax as the fear entity.', sourceIds:['hal'] },
  { year:2007, title:'Sinestro Corps War', era:'Modern', summary:'The yellow light of fear becomes an organized Corps-level threat, accelerating the Emotional Spectrum era.', sourceIds:['spectrum','sinestro'] },
  { year:2009, title:'Blackest Night', era:'Modern', summary:'Black rings and the dead turn the emotional spectrum into a universe-wide life-and-death crisis.', sourceIds:['blackest','spectrum'] },
  { year:2010, title:'Brightest Day', era:'Modern', summary:'The aftermath of Blackest Night shifts focus from death to the White Light of life and resurrected heroes.', sourceIds:['spectrum'] },
  { year:2011, title:'War of the Green Lanterns', era:'Modern', summary:'The Earth Lanterns are forced into conflict amid a crisis centered on the Corps and its power structure.', sourceIds:['corps'] },
  { year:2013, title:'Lights Out', era:'New 52', summary:'The Corps confronts a threat tied to the cost and source of emotional-spectrum energy.', sourceIds:['spectrum'] },
  { year:2014, title:'Godhead', era:'New 52', summary:'New Gods collide with Lantern mythology in a crossover spanning the spectrum-based titles.', sourceIds:['spectrum'] },
  { year:2019, title:'Far Sector', era:'Modern', summary:'Jo Mullein takes an experimental ring to the City Enduring in a science-fiction detective story far from Sector 2814.', sourceIds:['jo'] },
  { year:2025, title:'Green Lantern Corps Returns', era:'DC All In', summary:'A new Green Lantern Corps series reunites John, Jessica, Kyle, Guy, Jo and other ring-slingers for a renewed cosmic ensemble.', sourceIds:['glc2025'] }
];

export const reading = [
  { title:'Green Lantern: Rebirth', year:'2004–2005', why:'Modern reset point for Hal, Parallax and the restored Corps mythology.', tags:['Hal Jordan','Parallax','Corps'] },
  { title:'Sinestro Corps War', year:'2007–2008', why:'The fear-versus-will conflict that opens the door to the full Emotional Spectrum.', tags:['Sinestro','Hal Jordan','Corps'] },
  { title:'Blackest Night', year:'2009–2010', why:'The spectrum concept reaches event scale through the Black Lantern crisis.', tags:['Black Hand','Nekron','Spectrum'] },
  { title:'Green Lantern Corps', year:'2006–2011', why:'Best place to spend time with the institution itself: recruits, veterans, Oa and field teams.', tags:['Guy Gardner','John Stewart','Kilowog'] },
  { title:'Green Lanterns', year:'2016–2018', why:'A character-driven Earth partnership built around Simon Baz and Jessica Cruz.', tags:['Simon Baz','Jessica Cruz'] },
  { title:'Far Sector', year:'2019–2021', why:'A self-contained, inventive detective story that shows how flexible the Green Lantern premise can be.', tags:['Jo Mullein','City Enduring'] },
  { title:'Green Lantern: War Journal', year:'2023–2024', why:'A John Stewart-centered modern run with cosmic scale and personal stakes.', tags:['John Stewart'] },
  { title:'Green Lantern Corps', year:'2025–', why:'Current-era ensemble series bringing multiple Earth Lanterns back into a shared Corps book.', tags:['Corps','John Stewart','Jessica Cruz','Kyle Rayner','Guy Gardner','Jo Mullein'] }
];
